# Generated by Django 4.2.7 on 2025-10-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_planilla_b_final_1_planilla_b_final_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='losa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='otros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='pension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tarifa_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_egresos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_ingreso_oficina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_ingreso_ruta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='total_ingresos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='viaticos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
