# Generated by Django 4.2.7 on 2025-11-13 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=8, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato: '+56987654321' o '987654321'", regex='^\\+?56?[0-9]{8,9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.PROTECT, to='planillas.cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id_planilla', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horario_origen', models.TimeField()),
                ('horario_retorno', models.TimeField(blank=True, null=True)),
                ('ingreso_oficina', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ingreso_ruta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_produccion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('viaticos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('losa', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(db_column='bus_id', on_delete=django.db.models.deletion.PROTECT, to='planillas.bus')),
                ('cod_asistente', models.ForeignKey(blank=True, db_column='cod_asistente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_asistente', to='planillas.empleado', verbose_name='Asistente')),
                ('cod_conductor', models.ForeignKey(db_column='cod_conductor', on_delete=django.db.models.deletion.PROTECT, related_name='planillas_conductor', to='planillas.empleado', verbose_name='Conductor')),
                ('cod_origen', models.ForeignKey(db_column='cod_origen', on_delete=django.db.models.deletion.PROTECT, related_name='planillas_origen', to='planillas.ciudad', verbose_name='Ciudad de Origen')),
                ('cod_retorno', models.ForeignKey(blank=True, db_column='cod_retorno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_retorno', to='planillas.ciudad', verbose_name='Ciudad de Retorno')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'db_table': 'planilla',
            },
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['nombre_ciudad'], name='ciudad_nombre__5479e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudad',
            index=models.Index(fields=['activo'], name='ciudad_activo_d2ed55_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['patente'], name='bus_patente_e0b465_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['activo'], name='bus_activo_d1a6da_idx'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['fecha'], name='planilla_fecha_a2e363_idx'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['bus'], name='planilla_bus_id_3bce67_idx'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['cod_conductor'], name='planilla_cod_con_c806b0_idx'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['fecha_creacion'], name='planilla_fecha_c_88c890_idx'),
        ),
        migrations.AddConstraint(
            model_name='planilla',
            constraint=models.CheckConstraint(check=models.Q(('cod_conductor', models.F('cod_asistente')), _negated=True), name='conductor_diferente_asistente'),
        ),
        migrations.AddConstraint(
            model_name='planilla',
            constraint=models.CheckConstraint(check=models.Q(('total_produccion__gte', 0)), name='total_produccion_positivo'),
        ),
        migrations.AddConstraint(
            model_name='planilla',
            constraint=models.CheckConstraint(check=models.Q(('total_egresos__gte', 0)), name='total_egresos_positivo'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['email'], name='empleado_email_838c11_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['activo'], name='empleado_activo_b28016_idx'),
        ),
    ]
