# Generated by Django 5.1.1 on 2025-10-19 23:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(help_text='Imagen original subida por el usuario', upload_to='original_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])])),
                ('detected_rectangle', models.JSONField(blank=True, help_text='Coordenadas del rectángulo detectado por OpenCV', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Puntuación de confianza de la detección (0.0 - 1.0)', null=True)),
                ('processed_image', models.ImageField(blank=True, help_text='Imagen recortada y procesada', null=True, upload_to='processed_images/')),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
                ('algorithm_used', models.CharField(default='opencv_canny', help_text='Algoritmo usado para la detección', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo original en bytes', null=True)),
                ('image_dimensions', models.JSONField(blank=True, help_text='Dimensiones de la imagen original {width, height}', null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP del usuario que subió la imagen', null=True)),
            ],
            options={
                'verbose_name': 'Procesamiento de Documento',
                'verbose_name_plural': 'Procesamientos de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_processed', models.PositiveIntegerField(default=0)),
                ('successful_detections', models.PositiveIntegerField(default=0)),
                ('failed_detections', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Estadística de Procesamiento',
                'verbose_name_plural': 'Estadísticas de Procesamiento',
                'ordering': ['-date'],
            },
        ),
    ]
