# Generated by Django 4.2.7 on 2025-11-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('can_manage_conductores', 'Puede gestionar conductores'), ('can_manage_asistentes', 'Puede gestionar asistentes'), ('can_view_employee_reports', 'Puede ver reportes de empleados'), ('can_import_employees', 'Puede importar empleados desde Excel')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='planilla',
            options={'permissions': [('can_approve_planilla', 'Puede aprobar planillas'), ('can_reject_planilla', 'Puede rechazar planillas'), ('can_view_all_planillas', 'Puede ver todas las planillas'), ('can_export_planillas', 'Puede exportar planillas'), ('can_import_planillas', 'Puede importar planillas'), ('can_view_reports', 'Puede ver reportes avanzados')], 'verbose_name': 'Planilla', 'verbose_name_plural': 'Planillas'},
        ),
    ]
